### ISSUE TITLE
A failed backup results in parse errors

### ISSUE THREAD

**Issue by thoro** [sauspiel/rbarman#1]
Hi,

Exception is:

```
/usr/local/rvm/rubies/ruby-1.9.3-p545/lib/ruby/1.9.1/time.rb:267:in `parse': no time information in "None" (ArgumentError)
    from /usr/local/rvm/gems/ruby-1.9.3-p545/gems/rbarman-0.0.13/lib/rbarman/backup.rb:116:in `backup_start='
    from /usr/local/rvm/gems/ruby-1.9.3-p545/gems/rbarman-0.0.13/lib/rbarman/cli_command.rb:239:in `block in parse_backup_info_file'
    from /usr/local/rvm/gems/ruby-1.9.3-p545/gems/rbarman-0.0.13/lib/rbarman/cli_command.rb:235:in `each'
    from /usr/local/rvm/gems/ruby-1.9.3-p545/gems/rbarman-0.0.13/lib/rbarman/cli_command.rb:235:in `parse_backup_info_file'
    from /usr/local/rvm/gems/ruby-1.9.3-p545/gems/rbarman-0.0.13/lib/rbarman/cli_command.rb:69:in `block in backups'
    from /usr/local/rvm/gems/ruby-1.9.3-p545/gems/rbarman-0.0.13/lib/rbarman/cli_command.rb:68:in `each'
    from /usr/local/rvm/gems/ruby-1.9.3-p545/gems/rbarman-0.0.13/lib/rbarman/cli_command.rb:68:in `backups'
    from /usr/local/rvm/gems/ruby-1.9.3-p545/gems/rbarman-0.0.13/lib/rbarman/backups.rb:20:in `all'
    from ./check-barman.rb:78:in `check_last_wal_received'
    from ./check-barman.rb:202:in `<main>'
```

Problem is that a failed backup has no begin time, end time, as I'm not fluid in ruby I can't look for the exact code portion, I think you will be faster with that!

Here is the output from show-backup:

```
Backup 20140518T220002:
  Server Name       : xxx.xxx.xx
  Status            : FAILED
  Error:            : failure detecting data directory
bash-4.1$ barman show-backup xxx.xxx.xx 20140520T205254
Backup 20140520T205254:
  Server Name       : xxx.xxx.xx
  Status            : DONE
  PostgreSQL Version: 90302
  PGDATA directory  : /var/lib/pgsql/9.3/data

  Base backup information:
    Disk usage      : 10.1 GiB
    Timeline        : 1
    Begin WAL       : 00000001000000160000005A
    End WAL         : 00000001000000160000005A
    WAL number      : 1
    Begin time      : 2014-05-20 20:52:54.493173
    End time        : 2014-05-20 21:13:16.234241
    Begin Offset    : 40
    End Offset      : 2603104
    Begin XLOG      : 16/5A000028
    End XLOG        : 16/5A27B860

  WAL information:
    No of files     : 41
    Disk usage      : 211.6 MiB
    Last available  : 000000010000001600000083

  Catalog information:
    Retention Policy: VALID
    Previous Backup : 20140513T210335
    Next Backup     : - (this is the latest base backup)
```

---

After removing the failed backup the status is reported as it should

**Comment by hamann** [comment]
Thanks for reporting. I released 0.0.14 which should fix that
